# Generated by Django 4.1 on 2025-01-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_medicalrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="reports",
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="reports/")),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_reports",
                        to="mainapp.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
