# Generated by Django 4.1 on 2025-01-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_bloodtest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prescription", models.TextField(max_length=100)),
                ("dates", models.DateField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_prescriptions",
                        to="mainapp.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_prescriptions",
                        to="mainapp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicalUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanreport",
                    models.ImageField(
                        blank=True, null=True, upload_to="patient_report/"
                    ),
                ),
                ("reportdate", models.DateField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_reports",
                        to="mainapp.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_reports",
                        to="mainapp.patient",
                    ),
                ),
            ],
        ),
    ]
